# coding: utf-8

"""
    Finnhub Stock API

    OpenAPI spec for real-time stock quotes using Finnhub’s `/quote` endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_quote(self) -> None:
        """Test case for get_quote

        Get real-time quote
        """
        pass


if __name__ == '__main__':
    unittest.main()
