# coding: utf-8

"""
    Finnhub Stock API

    OpenAPI spec for real-time stock quotes using Finnhub’s `/quote` endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quote_response import QuoteResponse

class TestQuoteResponse(unittest.TestCase):
    """QuoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteResponse:
        """Test QuoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteResponse`
        """
        model = QuoteResponse()
        if include_optional:
            return QuoteResponse(
                c = 210.79,
                d = 12.26,
                dp = 6.1754,
                h = 211.2679,
                l = 206.75,
                o = 210.97,
                pc = 198.53,
                t = 1747080000
            )
        else:
            return QuoteResponse(
                c = 210.79,
                h = 211.2679,
                l = 206.75,
                o = 210.97,
                pc = 198.53,
                t = 1747080000,
        )
        """

    def testQuoteResponse(self):
        """Test QuoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
