# coding: utf-8

# flake8: noqa
"""
    Finnhub Stock API

    OpenAPI spec for real-time stock quotes using Finnhub’s `/quote` endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.quote_response import QuoteResponse
